export const BILLING_CONSTANTS = {
  DEFAULT_MAINTENANCE_FEE: 500,
  DEFAULT_ELECTRICITY_RATE_PER_UNIT: 8,
  DEFAULT_MOTOR_RATE_PER_HOUR: 15,
  DEFAULT_TAX_PERCENT: 5,
  DEFAULT_HARVEST_QUANTITY_KG: 25,
  DEFAULT_COMMISSION_PERCENT: 10,
  CURRENCY_SYMBOL: "₹",
};
